version: '3.0'

services:
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
#    environment:
#      MEMCACHED_USERNAME: root
#      MEMCACHED_PASSWORD: secret